<?php
$this->headTitle('Список турниров Интернет-Клуба "Что-Где-Когда"');
?>
<h1 align=center>Список турниров Интернет-Клуба "Что-Где-Когда"</h1>
<center>[<?= $this->actionLink("Прошлые турниры", "members", "old") ?>]</center><br/>
<table width="80%" border=0 cellpadding=5 cellspacing=2 align=center>
<tr bgcolor="#EEFFEE">
<td>Турнир <?= $this->actionLink("ИЧБ-8", "members", "turnir", array("id" => $this->turnir)) ?><br /><nobr><?= $this->Plural(count($this->teams), " команд", "а", "ы", "") ?>.</nobr></td></tr>
<?php foreach($this->teams as $team) {?>
<tr><td><?= $this->actionLink($team->imia, "members", "team", array("id" => $team->tid)) ?></td></tr>
<?php } ?>
</table>
