<?php
$this->headTitle("Личная карточка знатока");
?>
<h1 align=center>Личная карточка знатока</h1>

<table align=center border=2 cellpadding=0 cellspacing=0><tr><td><img src="<?= $this->baseUrl("foto/".$this->player->foto) ?>" border=0 alt="<?= $this->fotoalt ?>"></td></tr></table>

<h3 align=center><?= $this->player->famil ?> <?= $this->player->imia ?></h3>
<table align=center border=0 cellpadding=5 cellspacing=2>
<?= $this->printCardRow("День рождения:", $this->player->born) ?>
<?= $this->printCardRow("Город:", $this->player->city.", ".$this->player->country) ?>
<?= $this->printCardRow("E-mail:", $this->printEmail($this->player->email)) ?>

<tr class="cardhead"><td colspan=2 align=center>
<?= $this->actionLink("Изменить данные", "members", "playeredit", array("id" => $this->player->uid)) ?>
</td></tr>
</table>
<br/>

<table align=center border=0 cellpadding=5 cellspacing=2>
<tr class="cardhead"><th colspan=2 align="center">Участие в турнирах</th></tr>
<?php foreach($this->turs as $tur) {?>
<?= $this->printCardRow(
		"Турнир ".$this->actionLink($tur["turname"], "members", "turnir", array("id" => $tur["id"])), 
		"Команда ".$this->actionLink($tur["tname"], "members", "team", array("id" => $tur["tid"])), 
        $this->turnir == $tur["id"]) ?>
<?php } ?>
</table>
