<?php
$this->headTitle("Команда знатоков \"{$this->team["name"]}\"");
?>
<h1 align=center>Команда знатоков "<?= $this->team["name"] ?>", 
турнир "<?= $this->actionLink($this->turnir->imia, "members", "turnir", array("id" => $this->turnir->id)) ?>"</h1>

<table align=center border=0 cellpadding=5 cellspacing=2>
<?= $this->printCardRow("Номер команды:", $this->team["oldid"]) ?>
<?= $this->printCardRow("Командная страница:", $this->a($this->team["url"], $this->team["url"])) ?>
<?= $this->printCardRow("Контактный адрес:", $this->printEmail($this->team["contact"])) ?>
<tr class="cardhead"><td colspan=2 align=center>
<?= $this->actionLink("Изменить данные", "members", "teamedit", array("id" => $this->team["tid"])) ?>
</td></tr>
</table>
<br/>
<table align=center border=0 cellpadding=5 cellspacing=2>
<TR class="cardhead"><TD ALIGN="center" COLSPAN="4">Игроки команды "<?= $this->team["name"] ?>"</TD></TR>
<TR class="cardrow1"><TH>Имя</TH> <TH>E-mail</TH> <TH>Город</TH> <TH>Страна</TH></TR>
<?php for($i=0;$i<$this->maxplayers;$i++) {
	if(empty($this->team["pname$i"])) continue;
?>
<TR class="<?= $i%1?"cardrow1":"cardrow2" ?>">
<TD><?php if($i == 0) { ?><b>Капитан</b><?php } ?> 
<?= $this->actionLink($this->team["pfamil$i"]." ".$this->team["pname$i"], "members", "player", array("id" => $this->team["pid$i"])) ?>
</TD> 
<TD><?= $this->printEmail($this->team["pemail$i"]) ?> &nbsp;</TD> 
<TD><?= $this->team["pcity$i"] ?> &nbsp;</TD> 
<TD><?= $this->team["pcountry$i"] ?> &nbsp;</TD> 
</TR>
<?php } ?>
</table><br>
<?php if(isset($this->turs) && count($this->turs) > 1) { ?>
<center><B>В прошлых чемпионатах участвовала в: </B>
<?php foreach($this->turs as $tur) {
	if($tur["id"] == $this->team["turnir"]) continue;
	$this->placeholder('turs')->append($this->actionLink($tur["imia"], "members", "team", array("id" => $tur["tid"])));
}
?>
<?= $this->placeholder('turs')->setSeparator(", ") ?> 
</center>
<?php } ?>
