<?php
$this->headTitle('Регистрация');
//$this->dojo()->enable();
?>
<div id="welcome">
    <h1 align=center>Регистрация на турнир ИЧБ-<?= $this->ichb['name'] ?> сезона <?= $this->ichb['year'] ?> г.</h1>
Пожалуйста, заполните приведенную ниже форму.<br>
Названия обязательных полей выделены <span class="required">красным</span>. Первыми заполняйте, пожалуйста, данные для капитана команды.<br>
Очень просим Вас не лениться и заполнить все поля, по которым у Вас есть информация. Раз в год можно и потрудиться :).<br>
</div>
<div id="errors">
<?php
	$errors = $this->form->getMessages();
	$this->printErrors($errors, $this->form);
	if(isset($this->error)) {
		echo $this->printArr($this->error);
	}
?>
</div>

    <form action="<?= $this->form->getAction(); ?>" method="post" onSubmit="return JsChecks()" id="regform">
      <table bgcolor="white" cellpadding=4 cellspacing=2>
	    <?= $this->form->name->render() ?>
	    <?= $this->form->email->render() ?>
	    <?= $this->form->remail->render() ?>
	    <?= $this->form->sezon2008->render() ?>
	    <?= $this->form->url->render() ?>
	    <?= $this->form->kadres->render() ?>
	    <?= $this->form->klist->render() ?>
	    <?php $zlist = "Подписан ли кто-либо из команды на лист ZNATOK и/или Z-INFO?<br>".$this->form->zlist->renderRadioPlus(); ?>
	    <?= $this->form->zlist->renderTableRow($zlist) ?>
	    <?= $this->form->comment->render() ?>

	<tr><td colspan=2 bgcolor="white"><table id="players">
	      <tr><th>X</th><th class="required">Имя</th><th class="required">Фамилия</th><th class="required">Город</th><th>Страна</th><th>E-mail</th><th>Дата рожд. (дд/мм/гггг)</th><th>Пол</th></tr>
        <tr><th colspan=8>Капитан команды:</th></tr>
        <tr><th colspan=8>Если капитан уже есть в базе данных Интернет-клуба, достаточно заполнить только имя, фамилию и город и отметить поле "X".</th></tr>
              <tr>
              	<?= $this->form->pold0->render() ?>
              	<?= $this->form->pname0->render() ?>
              	<?= $this->form->pfamil0->render() ?>
              	<?= $this->form->pcity0->render() ?>
              	<?= $this->form->pcountry0->render() ?>
              	<?= $this->form->pemail0->render() ?>
              	<?= $this->form->pborn0->render() ?>
              	<?= $this->form->psex0->render() ?>
              </tr>
		<tr><th colspan=8>Игроки команды:</th></tr>
        <tr><th colspan=8>Если игрок уже есть в базе данных Интернет-клуба, достаточно заполнить только имя, фамилию и город и отметить поле "X".</th></tr>
        <?php for($i=1; $i<$this->maxplayers; $i++) {?>
        <tr>
        <?= $this->form->getElement("pold$i")->render() ?>
        <?= $this->form->getElement("pname$i")->render() ?>
        <?= $this->form->getElement("pfamil$i")->render() ?>
        <?= $this->form->getElement("pcity$i")->render() ?>
        <?= $this->form->getElement("pcountry$i")->render() ?>
        <?= $this->form->getElement("pemail$i")->render() ?>
        <?= $this->form->getElement("pborn$i")->render() ?>
        <?= $this->form->getElement("psex$i")->render() ?>
        </tr>
        <?php } ?>
      </table>
	    </td></tr>

	<tr><th colspan=2><?= $this->form->register->render() ?></th></tr>
      </table>
    </form>

<p></p><hr noshade align=center width="80%"/>
<table align=center width="80%"><tr><td align=right>
<i>Искренне Ваши</i>,<br>
координаторы ИЧБ,
Завкадр.<br>
</td></tr></table>
