<br/>
<div>Поставьте галочку возле имен игроков, которые уже играли в прошлых турнирах и зарегистрированы в базе.</div>
<br/>
<div class="hplayer-req hplayer hplayer-first">Имя</div>
<div class="hplayer-req hplayer">Фамилия</div>
<div class="hplayer-req hplayer">Город</div>
<div class="hplayer-req hplayer">Страна</div>
<div class="hplayer hplayer-short">Пол</div>
<div class="hplayer">Дата рождения</div>
<div class="hplayer">Email</div>
<br/>
