<center><SCRIPT LANGUAGE="JavaScript"><!--
var rb1_login = "znatoki";
var rb1_random = Math.round(Math.random() * 100000);
document.write('<iframe src="http://rotabanner.kulichki.net/cgi-bin/iframe/'+rb1_login+'?'+rb1_random +'" width=468 height=60 marginwidth=0 marginheight=0' +' scrolling=no frameborder=0><a '+ 'href="http://rotabanner.kulichki.net/cgi-bin/href/' + rb1_login+'?'+rb1_random +'" target=_top><img '+ 'src="http://rotabanner.kulichki.net/cgi-bin/banner/'+rb1_login+'?'+rb1_random +'" alt="Kulichki Networks" width=468 height=60 border=0 ismap></a></iframe>');
//-->
</script>
<noscript>
<iframe src="" width=468 height=60 marginwidth=0 marginheight=0 scrolling=no frameborder=0><a href="" target=_top><img src="http://rotabanner.kulichki.net/cgi-bin/banner/znatoki?1001" alt="Kulichki Networks" width=468 height=60 border=0 ismap></a>
	</iframe>
</noscript>
<!-- begin of Top100 code -->
<script id="top100Counter" type="text/javascript" src="http://cnt.rambler.ru/top100.jcn?216642"></script><noscript><a href="http://top100.rambler.ru/top100/"><img src="http://cnt.rambler.ru/top100.cnt?216642" alt="Rambler's Top100" width="81" height="63" border="0" /></a></noscript>
<!-- end of Top100 code -->
 <BR><Center><FONT SIZE=-1><A HREF="http://www.kulichki.com/advert">Реклама в Интернет</A><A
HREF="http://kulichki.kulichki.net/entsikl/">"Все Кулички"</A></FONT></Center></center>

