<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Default Application</title>
</head>
<body>
  <h1>Ошибка!</h1>
  <h2><?php echo $this->message ?></h2>

  <?php if ('development' == APPLICATION_ENV) { ?>

  <h3>Exception information:</h3>
  <p>
      <b>Message:</b> <?php echo $this->exception->getMessage() ?><br/>
      <b>In:</b> <?php echo $this->exception->getFile()?>:<?php echo $this->exception->getLine()?>
  </p>

  <h3>Stack trace:</h3>
  <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre><?php echo var_export($this->request->getParams(), true) ?>
  </pre>
  <?php } else { ?>
  <p>Произошла какая-то ошибка. Возможно, вы ввели неверные данные (например, номер команды, игрока, и т.п.)
  или набрали неверный URL. Или авторы сайта чего-то напутали. </p>
  <p>Если вам нужна помощь, обратитесь к Завкадру по адресу <a href="mailto:smalyshev@gmail.com?Subject=CHGK+site+error">smalyshev@gmail.com</a>.
  В своем сообщении процитируйте ошибку, указаную выше, адрес этой страницы и время, когда это произошло.
  </p>
  <?php  } ?>

</body>
</html>
