<?php 
$this->headTitle('Редактирование записи команды');
//$this->dojo()->enable();
?>
<h1 align="center">Данные команды номер <?= $this->tid?></h1>
<div id="errors" class="errors">
<?php
	$errors = $this->form->getMessages();
	$this->printErrors($errors, $this->form);
?>
</div>

    <form action="<?= $this->form->getAction(); ?>" method="post" onSubmit="return JsChecks()" id="regform">
      <table bgcolor="white" cellpadding=4 cellspacing=2>
	    <?= $this->form->tid->render() ?>
	    <?= $this->form->name->render() ?>
	    <?= $this->form->contact->render() ?>
	    <?= $this->form->remail->render() ?>
	    <?= $this->form->sezon2008->render() ?>
	    <?= $this->form->url->render() ?>
        <?php for($i=0; $i<$this->maxplayers; $i++) {
        	echo $this->form->getElement("oldpid$i")->render();
        }
        ?>
    <?= $this->printDataErrors($this->data_errors, "team", 2); ?>
	<tr><td colspan=2 bgcolor="white"><table id="players">
	      <tr><th>ID</th><th class="required">Имя</th><th class="required">Фамилия</th><th>Город</th><th>Страна</th><th>E-mail</th><th>Дата рожд.</th><th>Пол</th></tr>
        <tr><th colspan=8>Капитан команды:</th></tr>
              <tr>
              	<?= $this->form->pid0->render()  ?>
              	<?= $this->form->pname0->render() ?>
              	<?= $this->form->pfamil0->render() ?>
              	<?= $this->form->pcity0->render() ?>
              	<?= $this->form->pcountry0->render() ?>
              	<?= $this->form->pemail0->render() ?>
              	<?= $this->form->pborn0->render() ?>
              	<?= $this->form->psex0->render() ?>
              </tr>
	    <?= $this->printDataErrors($this->data_errors, "p0", 8); ?>
		<tr><th colspan=8>Игроки команды:</th></tr>
        <?php for($i=1; $i<$this->maxplayers; $i++) {?>
        <tr>
        <?= $this->form->getElement("pid$i")->render() ?>
        <?= $this->form->getElement("pname$i")->render() ?>
        <?= $this->form->getElement("pfamil$i")->render() ?>
        <?= $this->form->getElement("pcity$i")->render() ?>
        <?= $this->form->getElement("pcountry$i")->render() ?>
        <?= $this->form->getElement("pemail$i")->render() ?>
        <?= $this->form->getElement("pborn$i")->render() ?>
        <?= $this->form->getElement("psex$i")->render() ?>
        </tr>
	    <?= $this->printDataErrors($this->data_errors, "p$i", 8); ?>
        <?php } ?>
      </table>
	    </td></tr>

	<tr><th colspan=2><?= $this->form->save->render() ?>&nbsp;<?= $this->form->confirm->render() ?></th></tr>
      </table>
    </form>


