<?php
$this->headTitle('Список команд');
?>
<?php if(count($this->teams) == 0) { ?>
Нет зарегистрированных команд.
<?php } else { 
	foreach($this->teams as $id => $team) { ?>
<?= $this->actionLink("Команда {$team["name"]}", "members", "teamedit", array("id" => $id)) ?>
<?php if(($cnt = count($team["check"])) > 0 && (empty($this->known_err[$id]) || $cnt != $this->known_err[$id])) { echo "<span class=\"errors\">($cnt!)</span>"; } ?>
<br/>
<?php  
	}
} ?>
